sonar.projectKey=epn-event-manager
sonar.organization=epn-construccion-software
sonar.projectName=epn-event-manager

sonar.sources=constswgr2(2)/cleaning-crud/src,constswgr2(2)/epn-event-manager/src
sonar.tests=constswgr2(2)/cleaning-crud/src,constswgr2(2)/cleaning-crud/test,constswgr2(2)/epn-event-manager/src,constswgr2(2)/epn-event-manager/test
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=constswgr2(2)/cleaning-crud/coverage/lcov.info,constswgr2(2)/epn-event-manager/coverage/lcov.info
sonar.sourceEncoding=UTF-8
